platform:
  - x64

branches:
  only:
  - master
  - /\d\d\d\d\d\d\d\dT\d\d\d\d\d\dZ/

environment:
  global:
    GH_TOKEN:
      secure: L8UBEbi0DeooYcUYnviUbbsxZagptGEMtXzmNEAn+WgudBzAV32swuNMuxtv9s/d

    PYTHONUNBUFFERED: 1

  matrix:
    - TARGET_ARCH: x86
      PYVER: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda

    - TARGET_ARCH: x64
      PYVER: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64

    - TARGET_ARCH: x86
      PYVER: 35
      CONDA_INSTALL_LOCN: C:\\Miniconda35

    - TARGET_ARCH: x64
      PYVER: 35
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

    - TARGET_ARCH: x86
      PYVER: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda36

    - TARGET_ARCH: x64
      PYVER: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

install:
  - cmd: rmdir C:\cygwin /s /q

  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda.exe install -yq conda=4.3

  - cmd: conda.exe config --set auto_update_conda false

build: off

test_script:
  - cmd: distclean
  - cmd: .appveyor_scripts\\run.bat
  - cmd: check "out\\miniforge-py%PYVER%-*.exe"
  - cmd: if defined APPVEYOR_PULL_REQUEST_NUMBER (distclean)

cache:
  - out
