language: generic

os: osx
osx_image: xcode6.4

branches:
  only:
  - master
  - /\d\d\d\d\d\d\d\dT\d\d\d\d\d\dZ/

env:
  global:
    - secure: "H9/TtUUjfYH9BqhTd4sKitStP2qvjmR59m0g3BEOcgS7xfGVSBWcqz90zJUoePS6Epz1t6sbDyCDgoi3mz6CbB/GHWVAdwxuizM2I9pBfte9yVuOY6hL4sbWM4R3k4blzik7mLoZD6KroqLdFHiA6y7d8GA36ydwoJxRSs3Rm7pTgc2iwCuI+ZhD8egUMGwypjpQr34SjRyeXfEFnbou4hMOWFZm8YwC54VveHmeqFort266WNERhTq5gvwFPyoqs/ZMKCGcr+0uay5l9+iis2ebcvdzpNv/S9X1zJMVkrJC0tkEJ0OARey1d0bf6qt5iugRODr1gfnwx4mhDN4n2C6H+08DjCgIK05PvxIFMiB7QYRVzG+kOAEGy8tlwIRIiaroNRuCW9PyJYy3Gq5y0a/kqFwrr6YjdN//XIbWxLu2o7I7VR2+e0z2eh5Fwvs93Icm1KW0DmhdsVaAzSCe7q0GZCNvX6ub3Suwy2mPvKTIy5/Xe/Gq/c5FLconbvmrDY4kpdIFW2ZWVSdLSdjRdIu3NkePYcrWd2z39XGgpNYJN9IjfCOKN2FeiK7kyiizLaxjdXJQlRFTZOiNP/t+HjmVe6N8yfTFc+Nfr3IkfaE7RcJDL6FD/Xw3ZZDI5UE9ySP+IabN6GoRUQ9dETy3SMJAavU1oZyw0jFmoy7gWno="

    - PYTHONUNBUFFERED=1

  matrix:
    - PYVER="27"
    - PYVER="35"
    - PYVER="36"

before_install:
  - curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
  - /usr/bin/ruby ~/uninstall_homebrew -fq
  - rm ~/uninstall_homebrew

install:
  - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > miniconda.sh
  - bash miniconda.sh -b -p ~/miniconda
  - source ~/miniconda/bin/activate

  - conda config --set auto_update_conda false

script:
  - if [[ "$TRAVIS_TAG" == "" ]]; then
        ./distclean.py &&
        .travis_scripts/run.sh &&
        ./check.py "out/miniforge-py${PYVER}-*.sh";
    else
        ./publish.py --repo "${TRAVIS_REPO_SLUG}" --upload "out/*" &&
        ./distclean.py;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
        ./distclean.py;
    fi
  - mkdir -p out

cache:
  timeout: 600
  directories:
    - out
