version: 2

jobs:
  build_python_27:
    working_directory: ~/test
    machine: true
    environment:
      - PYTHONUNBUFFERED: 1
      - PYVER: "27"
    steps:
      - checkout
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          command: docker run -it -e HOST_USER_ID="$(id -u)" -e PYVER="${PYVER}" -e CIRCLE_PULL_REQUEST="${CIRCLE_PULL_REQUEST}" -v "$(pwd)":/home/conda/repo condaforge/linux-anvil /home/conda/repo/.circleci/run.sh
      - save_cache:
          key: build_python_27-{{ .Revision }}
          paths:
            - out

  build_python_35:
    working_directory: ~/test
    machine: true
    environment:
      - PYTHONUNBUFFERED: 1
      - PYVER: "35"
    steps:
      - checkout
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          command: docker run -it -e HOST_USER_ID="$(id -u)" -e PYVER="${PYVER}" -e CIRCLE_PULL_REQUEST="${CIRCLE_PULL_REQUEST}" -v "$(pwd)":/home/conda/repo condaforge/linux-anvil /home/conda/repo/.circleci/run.sh
      - save_cache:
          key: build_python_35-{{ .Revision }}
          paths:
            - out

  build_python_36:
    working_directory: ~/test
    machine: true
    environment:
      - PYTHONUNBUFFERED: 1
      - PYVER: "36"
    steps:
      - checkout
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          command: docker run -it -e HOST_USER_ID="$(id -u)" -e PYVER="${PYVER}" -e CIRCLE_PULL_REQUEST="${CIRCLE_PULL_REQUEST}" -v "$(pwd)":/home/conda/repo condaforge/linux-anvil /home/conda/repo/.circleci/run.sh
      - save_cache:
          key: build_python_36-{{ .Revision }}
          paths:
            - out

  test_release:
    working_directory: ~/test
    machine: true
    environment:
      - PYTHONUNBUFFERED: 1
    steps:
      - checkout
      - run:
          command: |
             git config --global user.name "Foo Bar"
             git config --global user.email "foo@bar.com"
      - run:
          command: python release.py
      - run:
          command: ( python release.py ) && false || true
      - run:
          command: python release.py --force

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_python_27
      - build_python_35
      - build_python_36
      - test_release
