version: 2

jobs:
  build_python_27:
    working_directory: ~/test
    machine: true
    environment:
      - PYVER: "27"
    steps:
      - checkout
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          command: docker run -it -e PYVER="${PYVER}" -v "$(pwd)":/repo -w /repo condaforge/linux-anvil .scripts/run.sh
      - run:
          command: docker run -it -e PYVER="${PYVER}" -v "$(pwd)":/repo -w /repo condaforge/linux-anvil ./check.py "out/miniforge-py${PYVER}-*.sh"

  build_python_35:
    working_directory: ~/test
    machine: true
    environment:
      - PYVER: "35"
    steps:
      - checkout
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          command: docker run -it -e PYVER="${PYVER}" -v "$(pwd)":/repo -w /repo condaforge/linux-anvil .scripts/run.sh
      - run:
          command: docker run -it -e PYVER="${PYVER}" -v "$(pwd)":/repo -w /repo condaforge/linux-anvil ./check.py "out/miniforge-py${PYVER}-*.sh"

  build_python_36:
    working_directory: ~/test
    machine: true
    environment:
      - PYVER: "36"
    steps:
      - checkout
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          command: docker run -it -e PYVER="${PYVER}" -v "$(pwd)":/repo -w /repo condaforge/linux-anvil .scripts/run.sh
      - run:
          command: docker run -it -e PYVER="${PYVER}" -v "$(pwd)":/repo -w /repo condaforge/linux-anvil ./check.py "out/miniforge-py${PYVER}-*.sh"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_python_27
      - build_python_35
      - build_python_36
